# Generated by Django 5.1.7 on 2025-06-24 21:35

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_attachment_tasklist_task_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='data',
            field=models.FileField(upload_to=task.models.GenerateFilePath()),
        ),
    ]
