# Generated by Django 5.1.7 on 2025-06-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='notcompleted_taks_count',
            new_name='notcompleted_tasks_count',
        ),
    ]
